### ISSUE TITLE
PdfSharp.Drawing.XGraphics:_gfx causes Exception

### ISSUE THREAD

**Issue by MuhSchaf** [ststeiger/PdfSharpNetStandard#5]
After creating a new Xamarin.Forms project and following the default steps of PDFSharp
[pdfsharp.net](http://www.pdfsharp.net/wiki/PDFsharpFirstSteps.ashx) , the app crashes.

**Error:** 
PdfSharp.Drawing.XGraphics:_gfx' (13) due to: Could not resolve type with token 01000060 from typeref (expected class 'System.Drawing.Graphics' in assembly 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:System.Drawing.Common, Version=4.0.0.0

As i understand it, the XGraphics accesses another Drawing Engine?
The following example works (commented out Code)

``` 
PdfDocument document = new PdfDocument();
PdfPage page = document.AddPage();

 //XGraphics gfx = XGraphics.FromPdfPage(page);
			
// Create a font

//XFont font = new XFont("Verdana", 20, XFontStyle.BoldItalic);
			
// Draw the text

//gfx.DrawString("Hello, World!", null, XBrushes.Black, new XRect(0, 0, page.Width, page.Height), XStringFormats.Center);

// Save the document...

const string filename = "HelloWorld.pdf";

document.Save(filename);

// ...and start a viewer.

//System.Diagnostics.Process.Start(filename);`

Thank you for your Net-Standard Port.

**Comment by ststeiger** [comment]
Where does your Xamarin.Forms application run ? 
Android or iOS ? 
While it is NetStandard, System.Drawing.Common functionality might not be implemented for Android/iOS. 

You could try PdfSharpCore, which does not use System.Drawing. 
https://github.com/ststeiger/PdfSharpCore

**Comment by MuhSchaf** [comment]
> Where does your Xamarin.Forms application run ?

I tried to run it on iOS (iPhone Simulator).

> You could try PdfSharpCore, which does not use System.Drawing.

Well, to be honest, i already found another library which worked for me. If this other library won´t hold up to the expectations of my customers, i will give PdfSharpCore a try.

Nevertheless, thank you very much for your quick reply and your work on tools everybody can benefit from.

**Comment by ststeiger** [comment]
@MuhSchaf: 3 days later is not actually fast, i was on holidays, but thanks anyway ;)

In case you run into any problems, for your case you best use 
https://github.com/roceh/PdfSharp.Xamarin
or 
https://github.com/akgulebubekir/PDFSharp.Xamarin.Forms


I only tested my stuff on Linux and Windows, not Android or iOS.

**Comment by francois974** [comment]
Hi , I have the same problem I think
I have tried sharpcore
XFont fontTexte = new XFont("Verdana", 12);

it compiles but when i try to debug I have this message :

Unhandled Exception:

System.TypeInitializationException: The type initializer for 'PdfSharpCore.Utils.FontResolver' threw an exception.
