### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by mfabrizi** [ststeiger/PdfSharpNetStandard#9]
I'd like to use PdfSharpNetStandard 0.0.14 in a UWP commercial application, but my company requires license information and there doesn't seem to be one associated with this repo.

**Comment by ststeiger** [comment]
It's the same license as pdfsharp. 
MIT License:
https://github.com/empira/PDFsharp/blob/master/LICENSE

**Comment by mfabrizi** [comment]
Thank you. I figured that was probably the case, but my company prefers to see a LICENSE file in the root of the repo and/or a link to the License in the About section here: https://github.com/ststeiger/PdfSharpNetStandard.

**Comment by ststeiger** [comment]
@mfabrizi: Added it in the about-section.

**Comment by ststeiger** [comment]
If you want it in the root of the repo, add it and send me a pull-request.

**Comment by ststeiger** [comment]
@mfabrizi: Merged.

**Comment by mfabrizi** [comment]
Thank you!
